-- gymhere · seed des salles (jeu de démo -> vraies salles à revendiquer)
-- A executer une seule fois dans l'éditeur SQL de ton projet Supabase, APRES schema.sql.
-- Toutes les salles sont insérées sans owner_id : elles sont visibles immédiatement
-- mais restent "à revendiquer" tant qu'un vrai gérant ne les réclame pas via l'app.

insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('gymnass', 'Gymnass', 'studio', '24 rue Laporte, 9e', 'Vaise', 45.7716, 4.8032, true, true, 'Lun–Ven 8h–21h', 'Sam 9h–13h · Dim fermé', '04 78 43 47 67', 'https://gymnass.fr', 0, 4.9, 48, '[]'::jsonb, '[]'::jsonb, '{"Coaching","Small group","Premium"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('basicfit-republique', 'Basic-Fit République', 'salle', '13-15 Rue de la République, 1er', 'Terreaux', 45.764, 4.835, false, false, 'Lun–Ven 6h–22h30', 'Sam–Dim 9h–19h', null, 'https://www.basic-fit.com', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('basicfit-villette', 'Basic-Fit Villette', 'salle', '44 Rue de la Villette, 3e', 'Villette-Gare', 45.76, 4.86, false, false, 'Lun–Ven 6h–22h30', 'Sam–Dim 9h–19h', null, 'https://www.basic-fit.com', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('basicfit-berliet', 'Basic-Fit Marius Berliet', 'salle', '76 Rue Marius Berliet, 8e', 'Mermoz', 45.728, 4.873, false, false, 'Ouvert 24h/24', 'Accès badge', null, 'https://www.basic-fit.com', 0, null, null, '[{"name":"Ouvert 24/7","icon":"24","tint":"#FFE9F1","color":"#FF1F6B"}]'::jsonb, '[]'::jsonb, '{"Ouvert 24/7","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('basicfit-marietton', 'Basic-Fit Marietton', 'salle', '93 Rue Marietton, 9e', 'Vaise', 45.769, 4.8, false, false, 'Jusqu’à 22h30', '', null, 'https://www.basic-fit.com', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('basicfit-audry', 'Basic-Fit Pierre Audry', 'salle', '54B Rue Pierre Audry, 9e', 'La Grivière', 45.786, 4.81, false, false, 'Ouvert 24h/24', 'Accès badge', null, 'https://www.basic-fit.com', 0, null, null, '[{"name":"Ouvert 24/7","icon":"24","tint":"#FFE9F1","color":"#FF1F6B"}]'::jsonb, '[]'::jsonb, '{"Ouvert 24/7","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('basicfit-gerland', 'Basic-Fit Gerland', 'salle', 'Av. Jean Jaurès, 7e', 'Gerland', 45.73, 4.829, false, false, 'Lun–Sam 6h–22h30', 'Dim 9h–19h', '03 66 33 33 44', 'https://www.basic-fit.com', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('basicfit-villeurbanne', 'Basic-Fit Villeurbanne', 'salle', '117 Bd de Stalingrad, Villeurbanne', 'Villeurbanne', 45.774, 4.88, false, false, 'Horaires non communiqués', '', null, 'https://www.basic-fit.com', 0, 3.5, 471, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('basicfit-venissieux', 'Basic-Fit Vénissieux', 'salle', '369 Route de Vienne, Vénissieux', 'Vénissieux', 45.696, 4.876, false, false, 'Ouvert 24h/24', 'Accès badge', null, 'https://www.basic-fit.com', 0, null, null, '[{"name":"Ouvert 24/7","icon":"24","tint":"#FFE9F1","color":"#FF1F6B"}]'::jsonb, '[]'::jsonb, '{"Ouvert 24/7","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('basicfit-vaulxenvelin', 'Basic-Fit Vaulx-en-Velin', 'salle', '236 Av. Franklin Roosevelt, Vaulx-en-Velin', 'Vaulx-en-Velin', 45.782, 4.912, false, false, 'Lun–Ven 6h–22h30', 'Sam–Dim 9h–19h', null, 'https://www.basic-fit.com', 0, 4.5, 970, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('fitnesspark-partdieu', 'Fitness Park Part-Dieu', 'salle', '129 Rue Servient (Tour Part-Dieu), 3e', 'Part-Dieu', 45.76, 4.858, false, false, 'Lun–Sam 6h–22h', 'Dim 10h–22h', null, 'https://www.fitnesspark.fr', 0, 4.3, 909, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('fitnesspark-confluence', 'Fitness Park Confluence', 'salle', '112 Cours Charlemagne, 2e', 'Confluence', 45.738, 4.8185, false, false, '7h30–22h', '', '04 82 91 15 26', 'https://www.fitnesspark.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('fitnesspark-terreaux', 'Fitness Park Terreaux', 'salle', '3 Rue Sainte-Marie-des-Terreaux, 1er', 'Terreaux', 45.768, 4.834, false, false, '6h–23h', '', null, 'https://www.fitnesspark.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('keepcool-partdieu', 'Keepcool Part-Dieu', 'salle', '17 Rue du Docteur Bouchut, 3e', 'Part-Dieu', 45.761, 4.856, false, false, '7j/7 6h–23h', '', null, 'https://www.keepcool.fr', 0, 4.2, 279, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('keepcool-montchat', 'Keepcool Montchat', 'salle', '184 Route de Genas, 3e', 'Montchat', 45.756, 4.879, false, false, '7j/7 6h–23h', '', null, 'https://www.keepcool.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('keepcool-felixfaure', 'Keepcool Félix Faure', 'salle', '172 Avenue Félix Faure, 3e', 'Grange Blanche', 45.749, 4.865, false, false, '7j/7 6h–23h', '', null, 'https://www.keepcool.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('keepcool-vaise', 'Keepcool Vaise', 'salle', '14 Rue Masaryk, 9e', 'Vaise', 45.774, 4.81, false, false, '7j/7 6h–23h', '', null, 'https://www.keepcool.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('keepcool-lyon8', 'Keepcool Lyon 8', 'salle', '106 Rue du Professeur Beauvisage, 8e', 'Monplaisir', 45.738, 4.869, false, false, '7j/7 6h–23h', '', null, 'https://www.keepcool.fr', 0, 4.4, 336, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('keepcool-confluence', 'Keepcool Confluence', 'salle', '35 Rue Dénuzière, 2e', 'Confluence', 45.742, 4.821, false, false, '7j/7 6h–23h', '', null, 'https://www.keepcool.fr', 0, 4.5, 268, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('keepcool-sky56', 'Keepcool Sky56', 'salle', '20 rue du Général Mouton-Duvernet (Tour Sky56), 3e', 'Part-Dieu', 45.75919, 4.85678, false, false, 'Lun–Ven 6h–22h', 'Sam 7h–20h · Dim 7h–14h, 15h–20h', '04 28 29 90 70', 'https://www.keepcool.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('keepcool-charpennes', 'Keepcool Villeurbanne-Charpennes', 'salle', '22 rue Gabriel Péri, Villeurbanne', 'Villeurbanne', 45.7695, 4.881, false, false, '7j/7 6h–23h', '', '04 37 43 64 03', 'https://www.keepcool.fr', 0, 4.3, 194, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('neoness-lyon8', 'Neoness Lyon 8', 'salle', '141 Rue Marius Berliet, 8e', 'Mermoz', 45.728, 4.873, false, false, 'Lun/Ven 9h–22h · Mar–Jeu 7h–22h', 'Sam 9h–19h · Dim 9h–18h', null, 'https://www.neoness.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('neoness-lyon6', 'Neoness Lyon 6', 'salle', '92 bis Rue d’Inkermann, 6e', 'Brotteaux', 45.768, 4.857, false, false, 'Lun/Ven 9h–22h · Mar–Jeu 7h–22h', 'Sam 9h–19h · Dim 9h–17h', null, 'https://www.neoness.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('onair-gambetta', 'On Air Gambetta', 'salle', '3 Place Aristide Briand, 3e', 'Saxe-Gambetta', 45.75, 4.846, false, false, 'Lun–Ven 6h–23h', 'Sam–Dim 8h–20h', null, 'https://www.onair-fitness.fr', 0, 4, 553, '[{"name":"Espace MMA/Boxing","icon":"🥊","tint":"#FFE9F1","color":"#FF1F6B"},{"name":"Espace femmes","icon":"♀","tint":"#FFE9F1","color":"#FF1F6B"},{"name":"Climatisée","icon":"❄","tint":"#EEF0FF","color":"#4D5BFF"}]'::jsonb, '[]'::jsonb, '{"MMA/Boxing","Espace femmes"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('onair-parmentier', 'On Air Parmentier', 'salle', '81 Rue Parmentier, 7e', 'Jean Macé', 45.746, 4.839, false, false, 'Horaires non communiqués', '', null, 'https://www.onair-fitness.fr', 0, 4.4, 282, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Cours collectifs"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('onair-gerland', 'On Air Gerland', 'salle', '60 Avenue Tony Garnier, 7e', 'Gerland', 45.733, 4.828, false, false, 'Lun–Ven 6h–23h', 'Sam–Dim 8h–20h', '04 78 24 49 79', 'https://www.onair-fitness.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Cours collectifs"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('onair-cordeliers', 'On Air Cordeliers', 'salle', '10 rue Président Carnot, 2e', 'Cordeliers', 45.76, 4.834, false, false, 'Lun–Ven 6h–23h', 'Sam–Dim 8h–20h', '04 72 31 24 55', 'https://www.onair-fitness.fr', 0, 4.9, 54, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Cours collectifs"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('onair-brotteaux', 'On Air Brotteaux', 'salle', '34 rue du Professeur Weill, 6e', 'Brotteaux', 45.769, 4.853, false, false, 'Lun–Ven 6h–23h', 'Sam–Dim 8h–20h', '09 55 39 49 71', 'https://www.onair-fitness.fr', 0, 4.3, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Cours collectifs"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('vitaliberte-lacassagne', 'Vita Liberté Lacassagne', 'salle', '169-171 Avenue Lacassagne, 3e', 'Grange Blanche', 45.748, 4.865, false, false, '7j/7 6h–23h', '', '04 72 33 78 50', 'https://www.vitaliberte.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Cardio"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('lappart-republique', 'L’Appart Fitness République', 'salle', '1 Rue de la République, 1er', 'Cordeliers', 45.763, 4.834, false, false, 'Horaires non communiqués', '', null, 'https://www.lappartfitness.com', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('lappart-prefecture', 'L’Appart Fitness Préfecture', 'salle', '4 Rue Pravaz, 3e', 'Part-Dieu', 45.76, 4.85, false, false, 'Horaires non communiqués', '', null, 'https://www.lappartfitness.com', 0, 4.4, 495, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Sans engagement"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('wellness-confluence', 'Wellness Sport Club Confluence', 'salle', '134 Cours Charlemagne, 2e', 'Confluence', 45.735, 4.818, false, false, 'Lun–Ven 7h–22h', 'Sam 8h–20h · Dim 8h–17h', '04 78 71 79 19', 'https://www.wellness-sportclub.fr', 0, null, null, '[{"name":"Piscine","icon":"~","tint":"#EEF0FF","color":"#4D5BFF"},{"name":"Hammam","icon":"♨","tint":"#DEFAF3","color":"#0E9E86"},{"name":"Sauna","icon":"♨","tint":"#DEFAF3","color":"#0E9E86"}]'::jsonb, '[]'::jsonb, '{"Piscine","Spa"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('wellness-vendome', 'Wellness Sport Club Vendôme', 'salle', '153 rue Vendôme, 3e', 'Vendôme', 45.762, 4.851, false, false, 'Lun–Ven 7h–22h', 'Sam 8h–20h · Dim 8h–17h', '04 78 71 02 21', 'https://www.wellness-sportclub.fr', 0, null, null, '[{"name":"Piscine","icon":"~","tint":"#EEF0FF","color":"#4D5BFF"},{"name":"Hammam","icon":"♨","tint":"#DEFAF3","color":"#0E9E86"},{"name":"Jacuzzi","icon":"~","tint":"#EEF0FF","color":"#4D5BFF"},{"name":"Sauna","icon":"♨","tint":"#DEFAF3","color":"#0E9E86"}]'::jsonb, '[]'::jsonb, '{"Piscine","Spa"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('wellness-gambetta', 'Wellness Sport Club Gambetta', 'salle', '100 Cours Gambetta, 7e', 'Guillotière', 45.749, 4.846, false, false, 'Lun–Ven 7h–22h', 'Sam 8h–20h · Dim 8h–17h', null, 'https://www.wellness-sportclub.fr', 0, null, null, '[{"name":"Piscine","icon":"~","tint":"#EEF0FF","color":"#4D5BFF"},{"name":"Hammam","icon":"♨","tint":"#DEFAF3","color":"#0E9E86"}]'::jsonb, '[]'::jsonb, '{"Piscine","Spa"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('wellness-villeurbanne', 'Wellness Sport Club Villeurbanne', 'salle', '56 rue Paul Verlaine, Villeurbanne', 'Villeurbanne', 45.769, 4.895, false, false, 'Lun–Ven 8h–22h', 'Sam 9h–20h · Dim 9h–17h', '04 37 43 32 32', 'https://www.wellness-sportclub.fr', 0, null, null, '[{"name":"Piscine","icon":"~","tint":"#EEF0FF","color":"#4D5BFF"},{"name":"Hammam","icon":"♨","tint":"#DEFAF3","color":"#0E9E86"}]'::jsonb, '[]'::jsonb, '{"Piscine","Spa"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('rituel-jeanjaures', 'Rituel Sport Club Jean-Jaurès', 'salle', '74 Av. Jean Jaurès, 7e', 'Jean Macé', 45.745, 4.838, false, false, '7j/7 6h–23h', '', null, 'https://www.rituel-sportclub.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Cardio"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('rituel-gambetta', 'Rituel Sport Club Gambetta', 'salle', '133 Grande Rue de la Guillotière, 7e', 'Guillotière', 45.749, 4.844, false, false, '7j/7 6h–23h', '', null, 'https://www.rituel-sportclub.fr', 0, 4.3, 364, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Cardio"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('uniq-partdieu', 'Uniqe Club', 'independante', '9 Rue des Cuirassiers, 3e', 'Part-Dieu', 45.759, 4.852, false, false, 'Horaires non communiqués', '', null, 'https://www.uniqeclub.com', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Salle indépendante"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('haltero-club-lyonnais', 'Haltéro Club Lyonnais', 'halterophilie', '53 Rue de Belfort, 4e', 'Croix-Rousse', 45.775, 4.829, false, false, '7j/7 7h–23h', 'Badge d’accès', '04 78 28 78 64', 'https://www.halteroclublyonnais.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Powerlifting","Club historique"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('victor-hugo-monplaisir', 'Club Victor Hugo Monplaisir', 'independante', '104 Avenue des Frères Lumière, 8e', 'Monplaisir', 45.738, 4.866, false, false, 'Accès salle 6h–22h', '7j/7 · Accueil 11h–13h, 15h–19h', '04 78 01 24 88', 'https://www.clubvictorhugo.com', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Salle indépendante"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('sisters-gym', 'Sisters’ Gym', 'feminin', '101 Rue Garibaldi, 6e', 'Brotteaux', 45.764, 4.854, false, false, 'Lun–Ven 11h30–20h30', 'Sam 10h30–13h30 · Dim fermé', '04 72 70 65 11', null, 0, null, null, '[{"name":"Espace femmes","icon":"♀","tint":"#FFE9F1","color":"#FF1F6B"}]'::jsonb, '[]'::jsonb, '{"100% féminin","Cours collectifs"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('l-form', 'L Form', 'feminin', '54 bis Rue Vendôme, 6e', 'Brotteaux', 45.77, 4.851, false, false, 'Lun–Jeu 8h30–21h', 'Ven 8h30–20h30 · Sam 9h–12h · Dim fermé', '04 78 93 92 14', 'https://www.l-form.fr', 0, 4.4, 27, '[{"name":"Espace femmes","icon":"♀","tint":"#FFE9F1","color":"#FF1F6B"},{"name":"Cours collectifs","icon":"◎","tint":"#F4F0FC","color":"#C81FFF"}]'::jsonb, '[]'::jsonb, '{"100% féminin","Cours collectifs"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('crossfit-gerland', 'CrossFit Gerland', 'crossfit', '18 Rue Croix Barret, 7e', 'Gerland', 45.737, 4.83, false, false, 'Horaires non communiqués', '', null, 'https://www.crossfit-gerland.com', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"CrossFit","Fonctionnel"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('crossfit-heka', 'CrossFit HEKA', 'crossfit', '31 Rue de Cuire, 4e', 'Croix-Rousse', 45.778, 4.828, false, false, 'Horaires non communiqués', '', null, 'https://www.crossfit-heka.fr', 0, 4.9, 150, '[]'::jsonb, '[]'::jsonb, '{"CrossFit","Fonctionnel"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('crossfit-secteur3', 'CrossFit Secteur 3', 'crossfit', '169-171 Avenue Lacassagne, 3e', 'Grange Blanche', 45.748, 4.865, false, false, 'Lun–Ven 7h–21h', 'Sam 9h30–16h', '06 50 91 92 28', 'https://www.crossfit-secteur3.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"CrossFit","Fonctionnel"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('bodyhit-bellecour', 'BodyHit Lyon Bellecour', 'ems', '39 Rue Thomassin, 2e', 'Bellecour', 45.759, 4.833, false, false, 'Sur rendez-vous', '', '04 72 77 62 33', 'https://bodyhit.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Électrostimulation","Coaching individuel"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('ironbodyfit-partdieu', 'Iron Bodyfit Lyon Part-Dieu', 'ems', '140 Cours Lafayette, 3e', 'Part-Dieu', 45.761, 4.851, false, false, 'Lun–Ven 10h30–14h, 16h30–20h', 'Sam 9h–13h · Dim fermé', '07 69 83 76 95', 'https://ironbodyfit-lyon.fr', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Électrostimulation","Coaching individuel"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('ironbodyfit-gerland', 'Iron Bodyfit Lyon Gerland', 'ems', '61 Allée d’Italie, 7e', 'Gerland', 45.729, 4.828, false, false, 'Sur rendez-vous', '', null, 'https://ironbodyfit.com', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Électrostimulation","Coaching individuel"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('ironbodyfit-vaise', 'Iron Bodyfit Lyon Vaise', 'ems', '24 Rue Laporte, 9e', 'Vaise', 45.7716, 4.8032, false, false, 'Sur rendez-vous', '', null, 'https://ironbodyfit.com', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Électrostimulation","Coaching individuel"}') on conflict (id) do nothing;
insert into public.gyms (id, name, category, address, quartier, lat, lng, certified, sponsored, hours, hours_sub, phone, website, price_min, google_rating, google_reviews, services, formulas, tags) values ('vo2max', 'Vo2 Max', 'independante', '9 Avenue Leclerc, 7e', 'Jean Macé', 45.744, 4.843, false, false, 'Ouvert 7j/7', '', '04 37 28 90 14', 'https://vo2max-lyon.com', 0, null, null, '[]'::jsonb, '[]'::jsonb, '{"Musculation","Cross-training"}') on conflict (id) do nothing;
